version: '3.3'

services:
  app:
    container_name: hotel-reservation
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - rabbitmq
    networks:
      - my-network
    command: sh -c 'sleep 15 && java -jar app.jar'
    env_file:
      - .env

  mysql:
    image: mysql:5.7
    restart: always
    env_file:
      - .env
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - my-network

  rabbitmq:
    image: "rabbitmq:3-management"
    restart: always
    env_file:
      - .env
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - my-network

networks:
  my-network:

volumes:
  my-db:
